version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"
    container_name: tweeter-frontend
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
    networks:
      - tweeter-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tweeter-backend
    environment:
      - DATABASE_URL=postgres://borko:borko@database:5432/tweeter
    ports:
      - "4000:4000"
    depends_on:
      - database
    networks:
      - tweeter-network

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: tweeter-database
    environment:
      - POSTGRES_USER=borko
      - POSTGRES_PASSWORD=borko
      - POSTGRES_DB=tweeter
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tweeter-network


networks:
  tweeter-network:
    driver: bridge

volumes:
  db-data:
